DEFAULT_CONFIG_NAME = "voicepaste.config.json"

DEFAULT_STT_URL = ""  # must be set in config; empty → startup error
DEFAULT_OLLAMA_URL = ""  # must be set in config; empty → startup error

DEFAULT_CLEAN_ENABLED = True
DEFAULT_CLEAN_MODEL_FALLBACK = "qwen3.5:cloud"
DEFAULT_LOCAL_CLEAN_TIMEOUT_MS = 2500
DEFAULT_CLOUD_CLEAN_TIMEOUT_MS = 3500
DEFAULT_MODEL_REQUEST_TIMEOUT_MS = 45000
DEFAULT_STT_TIMEOUT_MS = 30000
DEFAULT_PASTE_TIMEOUT_MS = 700

DEFAULT_MODE = "dictation"
DEFAULT_MODEL_PROFILE = "fast"
DEFAULT_FAST_MODEL = "llama3.2:3b"
DEFAULT_QUALITY_MODEL = "qwen2.5:3b"
DEFAULT_FAST_LOCAL_TIMEOUT_MS = 3200
DEFAULT_QUALITY_LOCAL_TIMEOUT_MS = 7000

DEFAULT_JOURNAL_PATH = r"%USERPROFILE%\Documents\VoicePaste\Journal"
DEFAULT_VOICE_PASTE_ROOT = r"%USERPROFILE%\Documents\VoicePaste\voice_paste"
DEFAULT_LOG_DIR = r"%USERPROFILE%\Documents\VoicePaste\Logs"
DEFAULT_LOG_RETENTION_DAYS = 30
DEFAULT_PHRASE_CORRECTIONS_PATH = r"%USERPROFILE%\Documents\VoicePaste\phrase_corrections.json"

DEFAULT_JOURNAL_PASTE = False
DEFAULT_MEETING_PASTE = False
DEFAULT_CLOUD_BREAKER_THRESHOLD = 3
DEFAULT_CLOUD_BREAKER_COOLDOWN_S = 60
DEFAULT_STT_HEALTH_CHECK_INTERVAL_S = 8
DEFAULT_WARMUP_ENABLED = True
DEFAULT_OLLAMA_KEEP_ALIVE = "20m"
DEFAULT_APP_MODE = "tray"
DEFAULT_CLOUD_FALLBACK_ENABLED = False
DEFAULT_CLAUDE_ENABLED = False
DEFAULT_CLAUDE_MODEL = "claude-3-5-haiku-latest"
DEFAULT_HIDE_ON_CLOSE = True
DEFAULT_AUDIO_FEEDBACK = True
DEFAULT_PARTIAL_TRANSCRIPT_ENABLED = False
DEFAULT_PARTIAL_UPDATE_INTERVAL_MS = 400
DEFAULT_SMART_FORMATTING_ENABLED = True
DEFAULT_VOICE_COMMANDS_ENABLED = True
DEFAULT_MEETING_SESSION_CHUNK_SECONDS = 20
DEFAULT_SNIPPETS_PATH = r"%USERPROFILE%\Documents\VoicePaste\snippets.json"
DEFAULT_HUD_ENABLED = True

